version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: security_db
    environment:
      POSTGRES_DB: security_db
      POSTGRES_USER: security_user
      POSTGRES_PASSWORD: security_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U security_user -d security_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build: ./backend
    container_name: security_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://security_user:security_password@postgres:5432/security_db
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - POLYGON_RPC_URL=https://polygon-mumbai.g.alchemy.com/v2/your-api-key
      - PRIVATE_KEY=your-private-key-for-blockchain-transactions
      - CONTRACT_ADDRESS=your-smart-contract-address
      - VIRUSTOTAL_API_KEY=your-virustotal-api-key
      - PHISHTANK_API_KEY=your-phishtank-api-key
      - UPLOAD_DIR=./uploads
      - MAX_FILE_SIZE=10485760
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: security_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

